total_backgrounds = ["Acolyte", "Anthropologist", "Archaeologist", "Athlete", "Charlatan", "City_Watch", "Clan_Crafter",
                     "Cloistered_Scholar", "Courtier", "Criminal", "Entertainer", "Faceless", "Faction_Agent",
                     "Far_Traveler", "Fisher", "Folk_Hero", "Gladiator", "Guild_Artisan", "Guild_Merchant",
                     "Haunted_One", "Hermit", "House_Agent", "Inheritor", "Investigator", "Knight",
                     "Knight_of_the_Order", "Marine", "Mercenary_Veteran", "Noble", "Outlander",
                     "Pirate", "Sage", "Sailor", "Shipwright", "Smuggler", "Soldier", "Spy", "Urban_Bounty_Hunter",
                     "Urchin", "Uthgardt_Tribe_Member", "Waterdhavian_Noble", "Black_Fist_Double_Agent",
                     "Dragon_Casualty", "Iron_Route_Bandit", "Phlan_Insurgent", "Stojanow_Prisoner",
                     "Ticklebelly_Nomad", "Caravan_Specialist", "Earthspur_Miner", "Harborfolk", "Aristocrat",
                     "Phlan_Refugee", "Cormanthor_Refugee", "Gate_Urchin", "Hillsfar_Merchant", "Hillsfar_Smuggler",
                     "Dissenter", "Initiate", "Vizier", "Inquisitor", "Azorius_Functionary", "Boros_Legionnaire",
                     "Dimir_Operative", "Golgari_Agent", "Gruul_Anarch", "Izzet_Engineer", "Orzhov_Representative",
                     "Rakdos_Cultist", "Selesnya_Initiate", "Simic_Scientist", "Grinner", "Volstrucker_Agent"]
