total_races = [
    # common_races
    "Dragonborn", "Dwarf",
    "Elf", "Gnome",
    "Half-elf", "Half-orc",
    "Halfling", "Human",
    "Tiefling",
# exotic_races =
    "Aarakocra",
    "Aasimar",
    "Firbolg",
    "Genasi",
    "Gith",
    "Goliath",
    "Kenku",
    "Locathah",
    "Tabaxi",
    "Tortle",
    "Triton",
# monstrous_races =
    "Bugbear",
    "Centaur",
    "Goblin",
    "Grung",
    "Hobgoblin",
    "Kobold",
    "Lizardfolk",
    "Minotaur",
    "Orc",
    "Yuan-Ti Pureblood",
# unearthed_arcana_races =
    "Dhamphir",
    "Hexblood",
    "Fairy",
    "Owlfolk",
    "Rabbitfolk",
    "Reborn",
# setting_specific_races =
    "Changeling",
    "Kalashtar",
    "Shifter",
    "Warforged",
    "Aetherborn",
    "Aven",
    "Khenra",
    "Kor",
    "Merfolk",
    "Naga",
    "Vampire",
    "Loxodon",
    "Simic Hybrid",
    "Vedalken",
    "Viashino",
    "Leonin",
    "Satyr", ]
